### ISSUE TITLE
Severe lack of documentation is really hurting this Repo

### ISSUE THREAD

**Issue by cvoege** [colejoh/timmy#1]
I've been a long time lurker here and I just have to make a post now to say this. The complete lack of documentation in this repo is making it almost impossible to make contributions, or even run the site to start with! There's also no tests, no README, and no CONTRIBUTING.md.

I love this repo and really want to see it succeed, but it's not going to if we don't address these problems.

**Comment by cvoege** [comment]
@colejoh hello???????????????????????????????????????///

**Comment by colejoh** [comment]
@cvoege your god is not my god
